version: 2

references:
    install_tox: &install_tox
        run:
            name: "Install tox"
            command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install tox

jobs:
    test:
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run:
                name: Install dependencies.
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
            - run:
                name: Lint code.
                command: |
                    . venv/bin/activate
                    mypy UnleashClient >> mypy.log
                    pylint UnleashClient -f parseable >> pylint.log
            - run:
                name: Run unit tests.
                command: |
                    . venv/bin/activate
                    py.test --html=pytest/results.html --junitxml=pytest/results.xml --self-contained-html --cov=UnleashClient tests/unit_tests
            - run:
                name: Run specification tests.
                command: |
                    . venv/bin/activate
                    py.test tests/specification_tests
            - store_test_results:
                path: pytest
            - store_artifacts:
                path: pylint.log
            - store_artifacts:
                path: mypy.log
            - run:
                name: Send code coverage to Coveralls
                command: |
                    . venv/bin/activate
                    coveralls
    tox-3.5:
        docker:
             - image: circleci/python:3.5
        steps:
            - checkout
            - *install_tox
            - run:
                name: "Run tox for Python 3.5"
                command: |
                    . venv/bin/activate
                    tox -e py35

    tox-3.6:
        docker:
             - image: circleci/python:3.6
        steps:
            - checkout
            - *install_tox
            - run:
                name: "Run tox for Python 3.6"
                command: |
                    . venv/bin/activate
                    tox -e py36

    tox-3.8:
        docker:
             - image: circleci/python:3.8-rc
        steps:
            - checkout
            - *install_tox
            - run:
                name: "Run tox for Python 3.8"
                command: |
                    . venv/bin/activate
                    tox -e py38

workflows:
    version: 2
    build_and_test:
        jobs:
            - test
            - tox-3.5:
                requires: 
                    - test
            - tox-3.6:
                requires: 
                    - test
            - tox-3.8:
                requires: 
                    - test
